import type { Workflow } from '@tierfall/cascade-core';

export interface EmitOptions {
  apiBaseUrl?: string;
}

export function emit(workflow: Workflow, opts: EmitOptions = {}): string {
  const baseUrl =
    opts.apiBaseUrl !== undefined
      ? JSON.stringify(opts.apiBaseUrl)
      : "process.env.CASCADE_API_URL ?? 'http://localhost:3000'";

  return `// Generated by @tierfall/cascade-compiler — DO NOT EDIT BY HAND.
// Workflow: ${workflow.name} (${workflow.id})
// Schema version: ${workflow.schemaVersion}
import { CascadeClient } from '@tierfall/cascade-sdk';

const workflow = ${JSON.stringify(workflow, null, 2)} as const;

export default async function main(input: Record<string, unknown> = {}): Promise<unknown> {
  const client = new CascadeClient({ baseUrl: ${baseUrl} });
  const run = await client.triggerWorkflow(workflow.id, { input });
  return run;
}
`;
}
