#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm exec lint-staged
pnpm typecheck
pnpm exec nx affected -t test --base=HEAD~1 --head=HEAD --parallel=3 || pnpm exec nx run-many -t test --parallel=3
